[package]
name = "skolaonline-util"
authors = ["Honbra <honbra@honbra.com>"]
description = "Utils for skolaonline-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
thiserror = "1.0.39"
